"""Initial migration

Revision ID: f64c8544603d
Revises: 
Create Date: 2024-07-01 10:46:58.300395

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'f64c8544603d'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('submissions', schema=None) as batch_op:
        batch_op.drop_index('ix_submissions_date')
        batch_op.drop_index('ix_submissions_user_id')

    op.drop_table('submissions')
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_index('ix_users_id')

    op.drop_table('users')
    op.drop_table('daily_challenges')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('daily_challenges',
    sa.Column('id', sa.BIGINT(), server_default=sa.text("nextval('daily_challenges_id_seq'::regclass)"), autoincrement=True, nullable=False),
    sa.Column('challenge_id', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('category', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('original_challenge', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('date', sa.DATE(), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name='daily_challenges_pkey'),
    sa.UniqueConstraint('challenge_id', name='daily_challenges_challenge_id_key'),
    postgresql_ignore_search_path=False
    )
    op.create_table('users',
    sa.Column('id', sa.INTEGER(), server_default=sa.text("nextval('users_id_seq'::regclass)"), autoincrement=True, nullable=False),
    sa.Column('email', sa.VARCHAR(length=64), autoincrement=False, nullable=False),
    sa.Column('password_hash', sa.VARCHAR(length=256), autoincrement=False, nullable=True),
    sa.Column('password_salt', sa.VARCHAR(length=64), autoincrement=False, nullable=True),
    sa.Column('name', sa.VARCHAR(length=128), autoincrement=False, nullable=True),
    sa.Column('total_votes', sa.INTEGER(), server_default=sa.text('0'), autoincrement=False, nullable=False),
    sa.Column('email_verified', sa.BOOLEAN(), server_default=sa.text('true'), autoincrement=False, nullable=False),
    sa.Column('google_user', sa.BOOLEAN(), server_default=sa.text('false'), autoincrement=False, nullable=False),
    sa.Column('is_admin', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.Column('login_streak', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('submission_streak', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('voting_streak', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('last_login_date', sa.DATE(), autoincrement=False, nullable=True),
    sa.Column('last_submission_date', sa.DATE(), autoincrement=False, nullable=True),
    sa.Column('last_voting_date', sa.DATE(), autoincrement=False, nullable=True),
    sa.Column('daily_votes', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('last_vote_date', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('votes_per_category', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='users_pkey'),
    sa.UniqueConstraint('email', name='users_email_key'),
    sa.UniqueConstraint('name', name='users_name_key'),
    postgresql_ignore_search_path=False
    )
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.create_index('ix_users_id', ['id'], unique=False)

    op.create_table('submissions',
    sa.Column('id', sa.BIGINT(), autoincrement=True, nullable=False),
    sa.Column('date', sa.DATE(), autoincrement=False, nullable=False),
    sa.Column('category', sa.VARCHAR(length=64), autoincrement=False, nullable=False),
    sa.Column('challenge_id', sa.VARCHAR(length=128), autoincrement=False, nullable=False),
    sa.Column('challenge', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('user_phrase', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('username', sa.VARCHAR(length=128), autoincrement=False, nullable=True),
    sa.Column('initial_score', sa.INTEGER(), server_default=sa.text('0'), autoincrement=False, nullable=False),
    sa.Column('votes', sa.INTEGER(), server_default=sa.text('0'), autoincrement=False, nullable=False),
    sa.Column('scored_first', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('final_submission', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['challenge_id'], ['daily_challenges.challenge_id'], name='submissions_challenge_id_fkey'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name='submissions_user_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='submissions_pkey')
    )
    with op.batch_alter_table('submissions', schema=None) as batch_op:
        batch_op.create_index('ix_submissions_user_id', ['user_id'], unique=False)
        batch_op.create_index('ix_submissions_date', ['date'], unique=False)

    # ### end Alembic commands ###
